editor: source

execute:
  cache: false
  freeze: false

project:
  type: website
  output-dir: docs
  render: [index.qmd]

title: "Test"
author: "Daniel Vartanian"
date: today
date-format: "YYYY-MM-DD"

website:
  favicon: images/favicon.png
  open-graph:
    image: images/og-image.png
    image-width: 2400
    image-height: 1600
    image-alt: "Testing, testing, ... 🎤"
  repo-url: https://github.com/danielvartan/test/
  site-url: https://danielvartan.github.io/test/
  issue-url: https://github.com/danielvartan/test/issues/
  repo-branch: main

format:
  revealjs:
    locale: en

google-scholar: false
